// Generated by scripts/protocol-vectors.mjs; do not edit.
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.30;
import {Protocol} from "../src/Protocol.sol";
import {ECDSA} from "@openzeppelin/contracts/utils/cryptography/ECDSA.sol";
contract ProtocolVectorsTest {
function testRequestAuthorizationMatchesTypeScript() public pure { Protocol.RequestAuthorization memory m;
m.protocolVersion=1;
m.requestId=0x72859a6ae50aa97f593f23df1c78bb1fd78cfc493fcef64159d6486223196833;
m.caller=0x7E5F4552091A69125d5DfCb7b8C2659029395Bdf;
m.budgetUsdc=10000000;
m.requestHash=0x6a5fe456ec2508ab5021d5941a5075e95ca1a495b129f144f42e665ab1d252ca;
m.executionAuthority=0x1efF47bc3a10a45D4B230B5d10E37751FE6AA718;
m.issuedAt=1791547200;
m.expiresAt=1791550800;
m.nonce=9007199254740993;
require(Protocol.hash(m)==0x3902ea726a3b20707667d6abd8f7195ea19202c12fc5671cbe91768231dd4253,"struct hash");
bytes32 d=keccak256(abi.encode(keccak256("EIP712Domain(string name,string version,uint256 chainId,address verifyingContract)"),keccak256("Stellarium"),keccak256("1"),uint256(84532),address(0x0000000000000000000000000000000000000010)));
require(keccak256(abi.encodePacked(hex"1901",d,Protocol.hash(m)))==0x31c79fbf3e034328541b9f5ff0d4d37a89cf97ab3f27f120d3bd7ad53bc841c7,"typed hash");
require(ECDSA.recover(0x31c79fbf3e034328541b9f5ff0d4d37a89cf97ab3f27f120d3bd7ad53bc841c7,hex"65f0f6b01b85f92ebcdcfe9da1483e2b4ec1c39acb0cf7c8adf3dc0e951217590259dbe3eaf4973006997ea35f85fd735373d8cfec37a4baf55e3249911b61741c") == 0x7E5F4552091A69125d5DfCb7b8C2659029395Bdf,"signed vector"); }
function testInvocationGrantMatchesTypeScript() public pure { Protocol.InvocationGrant memory m;
m.protocolVersion=1;
m.requestId=0x72859a6ae50aa97f593f23df1c78bb1fd78cfc493fcef64159d6486223196833;
m.authorizationHash=0x31c79fbf3e034328541b9f5ff0d4d37a89cf97ab3f27f120d3bd7ad53bc841c7;
m.invocationNonce=0x7ab1577440dd7bedf920cb6de2f9fc6bf7ba98c78c85a3fa1f8311aac95e1759;
m.providerPaymentIdentity=0x2B5AD5c4795c026514f8317c7a215E218DcCD6cF;
m.resourceId=0x915f28c4adf6e3b848b9f6bfd7acb012a2f8bae40cdf15df9b44d3f5c560d71e;
m.manifestRevision=1;
m.functionNameHash=0x513a6d19ef4581c264d9142eb2570c36bc2b3c546d42ee41fd0b6dd71fd60a61;
m.parametersHash=0x4dcda0849f23e8fc202a87a0faed3ceb7c3023098eeb66f1cb3be819aeebe997;
m.quoteId=0x238ad53218834f943da60c8bafd36c36692dcb35e6d76bdd93202f5c04c0baff;
m.grossPriceUsdc=1000000;
m.issuedAt=1791547201;
m.expiresAt=1791550800;
require(Protocol.hash(m)==0x93071215fa61fcdca91374f91761379ace3228c8d36e9043d680923508dd1a44,"struct hash");
bytes32 d=keccak256(abi.encode(keccak256("EIP712Domain(string name,string version,uint256 chainId,address verifyingContract)"),keccak256("Stellarium"),keccak256("1"),uint256(84532),address(0x0000000000000000000000000000000000000010)));
require(keccak256(abi.encodePacked(hex"1901",d,Protocol.hash(m)))==0x8a723bf83527c700b77bb808cdcf61564c099ec4bbb72da4ad6186b734f3ef78,"typed hash");
require(ECDSA.recover(0x8a723bf83527c700b77bb808cdcf61564c099ec4bbb72da4ad6186b734f3ef78,hex"8508187eae219818386f91c818fd9bd80071a5c75d1be7a3d79db36285d1f6b5021482c4e66a7f9e7d0c3f0a699fa75671380aa09d0841db899f91b0998532ef1b") == 0x1efF47bc3a10a45D4B230B5d10E37751FE6AA718,"signed vector"); }
function testExecutionReceiptMatchesTypeScript() public pure { Protocol.ExecutionReceipt memory m;
m.protocolVersion=1;
m.receiptId=0x083cb09a72849e6512faaeb13d1a9467c5aaaae976ef6ff7597fb61ed081e1a9;
m.requestId=0x72859a6ae50aa97f593f23df1c78bb1fd78cfc493fcef64159d6486223196833;
m.authorizationHash=0x31c79fbf3e034328541b9f5ff0d4d37a89cf97ab3f27f120d3bd7ad53bc841c7;
m.invocationId=0x8a723bf83527c700b77bb808cdcf61564c099ec4bbb72da4ad6186b734f3ef78;
m.invocationGrantHash=0x8a723bf83527c700b77bb808cdcf61564c099ec4bbb72da4ad6186b734f3ef78;
m.manifestRevision=1;
m.providerPaymentIdentity=0x2B5AD5c4795c026514f8317c7a215E218DcCD6cF;
m.paymentRecipient=0x2B5AD5c4795c026514f8317c7a215E218DcCD6cF;
m.receiptSigner=0xe1AB8145F7E55DC933d51a18c793F901A3A0b276;
m.resourceId=0x915f28c4adf6e3b848b9f6bfd7acb012a2f8bae40cdf15df9b44d3f5c560d71e;
m.functionNameHash=0x513a6d19ef4581c264d9142eb2570c36bc2b3c546d42ee41fd0b6dd71fd60a61;
m.parametersHash=0x4dcda0849f23e8fc202a87a0faed3ceb7c3023098eeb66f1cb3be819aeebe997;
m.responseHash=0x7f8b6b088b6d74c2852fc86c796dca07b44eed6fb3daf5e6b59f7c364db14528;
m.quoteId=0x238ad53218834f943da60c8bafd36c36692dcb35e6d76bdd93202f5c04c0baff;
m.grossPriceUsdc=1000000;
m.relay=0x6813Eb9362372EEF6200f3b1dbC3f819671cBA69;
m.relayFeeUsdc=100000;
m.executedAt=1791547202;
m.issuedAt=1791547202;
require(Protocol.hash(m)==0x47b7ceb492b75d8e02c0ef14421166549da36cd848e40a675e870dfb1ced02e3,"struct hash");
bytes32 d=keccak256(abi.encode(keccak256("EIP712Domain(string name,string version,uint256 chainId,address verifyingContract)"),keccak256("Stellarium"),keccak256("1"),uint256(84532),address(0x0000000000000000000000000000000000000010)));
require(keccak256(abi.encodePacked(hex"1901",d,Protocol.hash(m)))==0x07016b249f272083203c0cd3ebc9be9da9ebe67a8b8430c156d7a146e77b3732,"typed hash");
require(ECDSA.recover(0x07016b249f272083203c0cd3ebc9be9da9ebe67a8b8430c156d7a146e77b3732,hex"45ea38b9210ffa76c990ea38308eb9fac9217d65cd0ebebca4a21a9a5e2228d31cd242dff18264210936b89df71d5df68eb291f681bb733a0e312b188cb936431c") == 0xe1AB8145F7E55DC933d51a18c793F901A3A0b276,"signed vector"); }
function testAcceptanceMatchesTypeScript() public pure { Protocol.Acceptance memory m;
m.protocolVersion=1;
m.receiptHash=0x07016b249f272083203c0cd3ebc9be9da9ebe67a8b8430c156d7a146e77b3732;
m.issuedAt=1791547203;
require(Protocol.hash(m)==0x62654ebcdfe61d23dd5b6b081e2cb3d0c1085616408a42e15b914720684953fb,"struct hash");
bytes32 d=keccak256(abi.encode(keccak256("EIP712Domain(string name,string version,uint256 chainId,address verifyingContract)"),keccak256("Stellarium"),keccak256("1"),uint256(84532),address(0x0000000000000000000000000000000000000010)));
require(keccak256(abi.encodePacked(hex"1901",d,Protocol.hash(m)))==0xaf8dacedcbb07ad782864309ea4eeaaa70001a789daeb9763a5a762d9f0c1e97,"typed hash");
require(ECDSA.recover(0xaf8dacedcbb07ad782864309ea4eeaaa70001a789daeb9763a5a762d9f0c1e97,hex"4bf2e334749c1a2ce490e29bd9ac582c697bedaad02a3c22aa327a9bb631294e7d21993e42b4f37e2e3e315b15ae7158c988622370ddecc645b8dbea31995c191c") == 0x7E5F4552091A69125d5DfCb7b8C2659029395Bdf,"signed vector"); }
function testMonetizationManifestMatchesTypeScript() public pure { Protocol.MonetizationManifest memory m;
m.protocolVersion=1;
m.resourceId=0x915f28c4adf6e3b848b9f6bfd7acb012a2f8bae40cdf15df9b44d3f5c560d71e;
m.manifestRevision=1;
m.paymentIdentity=0x2B5AD5c4795c026514f8317c7a215E218DcCD6cF;
m.paymentRecipient=0x2B5AD5c4795c026514f8317c7a215E218DcCD6cF;
m.receiptSigner=0xe1AB8145F7E55DC933d51a18c793F901A3A0b276;
m.evidenceEncryptionPublicKey="X25519-key-test-vector";
m.usdc=0xE57bFE9F44b819898F47BF37E5AF72a0783e1141;
m.quoteRegistryId=0xd1adaede68d344519025e2ff574650cd99d3830fe6d274c7a7843cdc00e17938;
m.functions=new Protocol.FunctionQuote[](1);
m.functions[0]=Protocol.FunctionQuote("forecast",1000000,0x238ad53218834f943da60c8bafd36c36692dcb35e6d76bdd93202f5c04c0baff);
m.issuedAt=1791547200;
require(Protocol.hash(m)==0x9cbac0a0948ff1ca3d858778fe8b077d8db5e8313a7509b94a71114cf9dc2aec,"struct hash");
bytes32 d=keccak256(abi.encode(keccak256("EIP712Domain(string name,string version,uint256 chainId,address verifyingContract)"),keccak256("Stellarium"),keccak256("1"),uint256(84532),address(0x0000000000000000000000000000000000000010)));
require(keccak256(abi.encodePacked(hex"1901",d,Protocol.hash(m)))==0x2c1aa0c279d41b6a09d38acea90279b3f12da217530db8279a6aea0040bcc457,"typed hash");
require(ECDSA.recover(0x2c1aa0c279d41b6a09d38acea90279b3f12da217530db8279a6aea0040bcc457,hex"5af9c5dfffa02b5a533b3f2815455f0f57e0f88b0f1f0197088486c72d4a20097b8d9c96a91f17fa1c716b38b6b05a879c2eb4993a811de97669c04cbfb8a9071c") == 0x2B5AD5c4795c026514f8317c7a215E218DcCD6cF,"signed vector"); }
}
