import fs from "node:fs";
import { hashStruct } from "viem";
import { privateKeyToAccount } from "viem/accounts";
import {
    types,
    typedHash,
    hashName,
    receiptId,
} from "../dist/protocol/typed-data.js";
import {
    canonicalJson,
    hashRequest,
    hashParameters,
    hashValue,
} from "../dist/protocol/canonical.js";
const domain = {
    name: "Stellarium",
    version: "1",
    chainId: 84532,
    verifyingContract: "0x0000000000000000000000000000000000000010",
};
const key = (i) => `0x${i.toString(16).padStart(64, "0")}`;
const address = (i) => privateKeyToAccount(key(i)).address;
const source =
    'request Forecast { const weather: example.Weather return weather.forecast(city: "Oslo") }';
const parameters = [{ name: "city", value: "Oslo" }];
const authorization = {
    protocolVersion: 1,
    requestId: hashName("request"),
    caller: address(1),
    budgetUsdc: 10_000_000n,
    requestHash: hashRequest(source),
    executionAuthority: address(4),
    issuedAt: 1791547200n,
    expiresAt: 1791550800n,
    nonce: 9007199254740993n,
};
const authHash = typedHash("RequestAuthorization", {
    domain,
    message: authorization,
});
const grant = {
    protocolVersion: 1,
    requestId: authorization.requestId,
    authorizationHash: authHash,
    invocationNonce: hashName("nonce"),
    providerPaymentIdentity: address(2),
    resourceId: hashName("example.Weather"),
    manifestRevision: 1n,
    functionNameHash: hashName("forecast"),
    parametersHash: hashParameters(parameters),
    quoteId: hashName("quote"),
    grossPriceUsdc: 1_000_000n,
    issuedAt: 1791547201n,
    expiresAt: authorization.expiresAt,
};
const invocationId = typedHash("InvocationGrant", { domain, message: grant });
const receipt = {
    protocolVersion: 1,
    receiptId: receiptId(domain, authorization.requestId, invocationId),
    requestId: authorization.requestId,
    authorizationHash: authHash,
    invocationId,
    invocationGrantHash: invocationId,
    manifestRevision: 1n,
    providerPaymentIdentity: address(2),
    paymentRecipient: address(2),
    receiptSigner: address(5),
    resourceId: grant.resourceId,
    functionNameHash: grant.functionNameHash,
    parametersHash: grant.parametersHash,
    responseHash: hashValue(12),
    quoteId: grant.quoteId,
    grossPriceUsdc: grant.grossPriceUsdc,
    relay: address(3),
    relayFeeUsdc: 100_000n,
    executedAt: 1791547202n,
    issuedAt: 1791547202n,
};
const acceptance = {
    protocolVersion: 1,
    receiptHash: typedHash("ExecutionReceipt", { domain, message: receipt }),
    issuedAt: 1791547203n,
};
const manifest = {
    protocolVersion: 1,
    resourceId: grant.resourceId,
    manifestRevision: 1n,
    paymentIdentity: address(2),
    paymentRecipient: address(2),
    receiptSigner: address(5),
    evidenceEncryptionPublicKey: "X25519-key-test-vector",
    usdc: address(6),
    quoteRegistryId: hashName("registry"),
    functions: [
        {
            name: "forecast",
            grossPriceUsdc: 1_000_000n,
            quoteId: grant.quoteId,
        },
    ],
    issuedAt: 1791547200n,
};
const messages = {
    RequestAuthorization: authorization,
    InvocationGrant: grant,
    ExecutionReceipt: receipt,
    Acceptance: acceptance,
    MonetizationManifest: manifest,
};
const vectors = {
    canonicalizationVersion: 1,
    requestscriptVersion: "1.0.5",
    domain,
    source,
    requestHash: hashRequest(source),
    parameters,
    parametersHash: hashParameters(parameters),
    values: [null, { b: 2, a: "hello" }, ["12", true]].map((value) => ({
        value,
        canonicalJson: canonicalJson(value),
        hash: hashValue(value),
    })),
    signatures: Object.entries(messages).map(([primaryType, message]) => ({
        primaryType,
        message,
        structHash: hashStruct({ data: message, primaryType, types }),
        typedHash: typedHash(primaryType, { domain, message }),
    })),
};
for (const vector of vectors.signatures) {
    const account = privateKeyToAccount(
        key(
            {
                RequestAuthorization: 1,
                InvocationGrant: 4,
                ExecutionReceipt: 5,
                Acceptance: 1,
                MonetizationManifest: 2,
            }[vector.primaryType],
        ),
    );
    vector.signedBy = account.address;
    vector.signature = await account.signTypedData({
        domain,
        types,
        primaryType: vector.primaryType,
        message: vector.message,
    });
}
const json =
    JSON.stringify(
        vectors,
        (_, v) => (typeof v === "bigint" ? v.toString() : v),
        2,
    ) + "\n";
let solidity =
    '// Generated by scripts/protocol-vectors.mjs; do not edit.\n// SPDX-License-Identifier: MIT\npragma solidity ^0.8.30;\nimport {Protocol} from "../src/Protocol.sol";\nimport {ECDSA} from "@openzeppelin/contracts/utils/cryptography/ECDSA.sol";\ncontract ProtocolVectorsTest {\n';
for (const vector of vectors.signatures) {
    const name = vector.primaryType;
    solidity += `function test${name}MatchesTypeScript() public pure { Protocol.${name} memory m;\n`;
    for (const [key, value] of Object.entries(vector.message)) {
        if (key === "functions") {
            solidity += "m.functions=new Protocol.FunctionQuote[](1);\n";
            solidity += `m.functions[0]=Protocol.FunctionQuote("forecast",1000000,${grant.quoteId});\n`;
        } else {
            const field = types[name].find((f) => f.name === key);
            const literal =
                field.type === "string" ? JSON.stringify(value) : String(value);
            solidity += `m.${key}=${literal};\n`;
        }
    }
    solidity += `require(Protocol.hash(m)==${vector.structHash},"struct hash");\n`;
    solidity += `bytes32 d=keccak256(abi.encode(keccak256("EIP712Domain(string name,string version,uint256 chainId,address verifyingContract)"),keccak256("Stellarium"),keccak256("1"),uint256(84532),address(0x0000000000000000000000000000000000000010)));\nrequire(keccak256(abi.encodePacked(hex"1901",d,Protocol.hash(m)))==${vector.typedHash},"typed hash");\nrequire(ECDSA.recover(${vector.typedHash},hex"${vector.signature.slice(2)}") == ${vector.signedBy},"signed vector"); }\n`;
}
solidity += "}\n";
for (const [path, contents] of [
    ["docs/protocol-vectors.json", json],
    ["contracts/test/ProtocolVectors.t.sol", solidity],
]) {
    if (process.argv.includes("--check")) {
        if (fs.readFileSync(path, "utf8") !== contents)
            throw new Error(`Stale protocol vectors: ${path}`);
    } else fs.writeFileSync(path, contents);
}
console.log(
    "Protocol canonicalization and TypeScript/Solidity signature vectors verified.",
);
